version: "3.9"

networks: #networks
  redenova: #nome da rede
    driver: bridge #tipo de rede

services: #containers
  postgres: #container
    image: postgres #nome da imagem
    container_name: postgresdb #nome do container
    volumes: #volume do container
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql #realiza a criação do usuário docker, do database e da tabela
      - ./insert.sql:/docker-entrypoint-initdb.d/insert.sql #realiza a inserção de dois registros na tabela recém criada
    ports: #porta de acesso
      - 5000:5432 #porta pc:container
    networks: #network conectada
      - redenova #nome da network conectada
    environment: #variabel de ambiente
      POSTGRES_USER: postgres #usuario do banco
      POSTGRES_PASSWORD: postgres #senha do banco
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - redenova
    depends_on:
      - postgres
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana: